### PR TITLE
Album Page

### PR DESCRIPTION
**Pull request by szainmehdi**
A missing step and a possible design optimization was crucially missing. This PR adds a dedicated page for albums.

image

This will allow users to directly link to an album, which is absolutely vital when it comes to reciters with many albums.

This also opens up the possibility of optimizing the Reciter page to show only album cards, to allow for faster load times. This is not something done today, but may be something we look into in the future.

### CODE REVIEW

**Comment by shea786** [comment]
When we click on the album year from the audio player, it is going to reciter page instead of album page

**Comment by shea786** [comment]
Also now that we have album as a single entity,
I think we should include album search back
Also i think we should have popular albums?
What you think?

**Comment by szainmehdi** [comment]
> Also now that we have album as a single entity,
> I think we should include album search back
> Also i think we should have popular albums?
> What you think?

I agree to adding a popular albums or more likely, a "Latest Releases" section to the homepage, but that'll be done separately.

As far as albums in the search go, I don't know yet. But again, separately.

**Comment by szainmehdi** [comment]
> When we click on the album year from the audio player, it is going to reciter page instead of album page

Yea, I didn't add these functionalities in this PR. I think that's separate as well. :)

**Comment by shea786** [comment]
@szainmehdi 

Sure they are separate tasks so approving on that basis

**Pull request merged**
