### PR TITLE
Event Sourcing: Popular Entities

### PR DESCRIPTION
**Pull request by szainmehdi**

### CODE REVIEW

**Comment by szainmehdi** [comment]
@shea786 We'll have to re-run `event:init` and `event:replay` for this branch.

**Comment by shea786** [comment]
I'm not sure how we are doing this in production but we might need to clear the Laravel cache. Or it might be because of how my system is setup not sure but i had to clear the route cache as well as config cache etc otherwise the RouteBinding was returning null from the database

`dev art cache:clear`
`dev art route:clear`
`dev art config:clear`
`dev art view:clear` -> might not need this one as we are not using views from Laravel

**Comment by szainmehdi** [comment]
Got it. I think we already did that for automated builds. 

Other than that, how does this PR look @shea786?

**Comment by shea786** [comment]
Apart from those points, I think time is being stored in database 1 hour behind my current time zone, not sure what  it is for you, And is that even a worry

Apart from that, I'm.happt with everything else

**Comment by szainmehdi** [comment]
@shea786 The time in the database is stored in UTC / GMT. You're on British Summer Time which is one hour ahead. I'm on Pacific Daylight Time which is 7 hours behind. 

It's working correctly :)

**Comment by shea786** [comment]
@szainmehdi happy to approve

**Pull request merged**
